# Generated by Django 2.1.7 on 2019-04-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intersection',
            old_name='idIntersecion',
            new_name='idIntersection',
        ),
    ]
