# Generated by Django 2.1.7 on 2019-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190408_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='beginning',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ending',
            field=models.DateField(auto_now_add=True),
        ),
    ]
